apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-gitops-repo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/team-xquare/xquare-onpremise-project-gitops-repo.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: false
      include: "applicationset.yaml"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - Validate=true
